package com.appinspire.imagedesigns;


/**
 * Created by Bilal Rashid on 1/6/2018.
 */

public class Products {
    public String click_link;
    public String image_link;
    public String product_name;

    public Products(String link, String image, String name) {
        this.click_link = link;
        this.image_link = image;
        this.product_name = name;

    }

    public static Products[] getProducts() {
        return new Products[]{
                new Products("http://s.click.aliexpress.com/e/R7QFYzb",
                        "https://ae01.alicdn.com/kf/HTB1_70ORXXXXXXQapXXq6xXFXXXz/8-PCS-2017-New-Safe-Bowknot-Rabbit-Head-Hairpins-Ornaments-Hair-Jewelry-Girls-Accessories-Children-Hair.jpg_220x220.jpg",
                        "AliExpress.com Product - 8 PCS 2017 New Safe Bowknot Rabbit Head Hairpins Ornaments Hair Jewelry Girls Accessories Children Hair Clip Kids Barrettes"),
                new Products("http://s.click.aliexpress.com/e/2zJuRzR",
                        "https://ae01.alicdn.com/kf/HTB1SE1JOpXXXXbWapXXq6xXFXXX5/12pcs-Children-hair-accessories-girl-princess-cute-Crystal-Flower-shape-mini-hair-pliers-Crab-claw-Clip.jpg_220x220.jpg",
                        "AliExpress.com Product - 4pcs Children hair accessories BB girl bride cute flower shape mini hair pliers Crab claw folder gifts Wholesale and Retail"),
                new Products("http://s.click.aliexpress.com/e/E6IuzZz",
                        "https://ae01.alicdn.com/kf/HTB1cfp0lsLJ8KJjy0Fnq6AFDpXay/Chamsgend-meia-Hot-Winter-Warm-Christmas-Cartoon-Print-Long-Socks-Women-Girls-Gift-Meias-71026-Drop.jpg_220x220.jpg",
                        "AliExpress.com Product - Chamsgend meia Hot Winter Warm Christmas Cartoon Print Long Socks Women Girls Gift Meias 71026 Drop Shipping"),
                new Products("http://s.click.aliexpress.com/e/yZbaYjM",
                        "https://ae01.alicdn.com/kf/HTB17oPNhcrI8KJjy0Fhq6zfnpXag/Bracelets-Diomedes-Gussy-Life-Wholesale-New-Men-Fashion-Leather-Charm-Bangle-Handmade-Round-Rope-Jan17.jpg_220x220.jpg",
                        "AliExpress.com Product - Gussy Life wholesale New Men Fashion Leather Bracelets Charm Bangle Handmade Round Rope Jan17"),
                new Products("http://s.click.aliexpress.com/e/eu3bUj2",
                        "https://ae01.alicdn.com/kf/HTB16.9bgNPI8KJjSspfq6ACFXXaL/Natural-Stone-Black-Beads-Leopard-Strand-Bracelet-Men-Jewelry-Animal-Bangles-Homme-Femme-Chain-Ethnic-Handmade.jpg_220x220.jpg",
                        "AliExpress.com Product - Natural Stone Black Beads Leopard Strand Bracelet Men Jewelry Animal Bangles Homme Femme Chain Ethnic Handmade bracelets kralen"),
                new Products("http://s.click.aliexpress.com/e/MFyBiuj",
                        "https://ae01.alicdn.com/kf/HTB1BQtISVXXXXaFaXXXq6xXFXXXU/JewelryPalace-Princess-Diana-3-2-ct-Created-Blue-Sapphire-Ring-925-Sterling-Silver-Engagement-Rings-For.jpg_220x220.jpg",
                        "AliExpress.com Product - Kate Princess Diana William 2.5ct Blue Sapphire Engagement Wedding Ring For Women Love Lady Set 925 Sterling Silver Fine Jewelry"),
                new Products("http://s.click.aliexpress.com/e/QBqjIyj",
                        "https://ae01.alicdn.com/kf/HTB1woA2ajgy_uJjSZKbq6xXkXXaM/JewelryPalace-Bow-Anniversary-Wedding-Ring-For-Women-Soild-925-Sterling-Silver-Jewelry-For-Girl-Party-Friend.jpg_220x220.jpg",
                        "AliExpress.com Product - JewelryPalace Bow Cubic Zirconia Anniversary Wedding Ring For Women Soild 925 Sterling Silver Jewelry For Girl Party Friend Gift"),
                new Products("http://s.click.aliexpress.com/e/yvf6yVz",
                        "https://ae01.alicdn.com/kf/HTB1.6iIjhTI8KJjSspiq6zM4FXai/20pcs-Fit-8-10-12-14-16-18-20-25-30mm-One-Sided-Double-Hanging-Classical.jpg_220x220.jpg",
                        "AliExpress.com Product - 12pcs 12mm inner size ( 21*14mm outer size ) Vintage Antique Silver Tone Zinc Alloy Cameo Cabochon Base Setting Connector"),
                new Products("http://s.click.aliexpress.com/e/rZVByJ6",
                        "https://ae01.alicdn.com/kf/HTB1Qb0MgcrI8KJjy0Fh762fnpXaK/EN_300_250.png",
                        "AliExpress Event for Baby Products"),
                new Products("http://s.click.aliexpress.com/e/A272vRN",
                        "https://ae01.alicdn.com/kf/HTB1BTdLgdfJ8KJjy0Fe760KEXXa8/EN_300_250.png",
                        "AliExpress Fashion Event"),
                new Products("http://s.click.aliexpress.com/e/MByRZfA",
                        "https://ae01.alicdn.com/kf/HTB1eOsUf22H8KJjy0Fc761DlFXaL/EN_300_250.png",
                        "AliExpress Fashion Products Event"),
                new Products("http://s.click.aliexpress.com/e/aqFujaq",
                        "https://ae01.alicdn.com/kf/HTB16PYbSpXXXXbSXXXXq6xXFXXXI/2Pcs-Silicone-Gel-Bunion-Splint-Big-Toe-Separator-Overlapping-Spreader-Protection-Corrector-Hallux-Valgus-Foot-Massager.jpg_220x220.jpg",
                        "AliExpress.com Product - 2Pcs Silicone Gel Bunion Splint Big Toe Separator Overlapping Spreader Protection Corrector Hallux Valgus Foot Massager C147"),
                new Products("http://s.click.aliexpress.com/e/rVvVBmY",
                        "https://ae01.alicdn.com/kf/HTB1CkYFXamgSKJjSsplq6yICpXa2/6Boxes-Hexagon-Chunky-Glitter-Mermaid-Sequins-Paillette-Shiny-Nail-Flakes-Glitter-Set-Manicure-3D-Nail-Art.jpg_220x220.jpg",
                        "AliExpress.com Product - 6Boxes Hexagon Chunky Glitter Mermaid Sequins Paillette Shiny Nail Flakes Glitter Set Manicure 3D Nail Art Decorations"),
                new Products("http://s.click.aliexpress.com/e/zZnMn2B",
                        "https://ae01.alicdn.com/kf/HTB1EkSSRpXXXXcyXFXXq6xXFXXXP/2017-Hot-Sales-40CM-Inflatable-World-Globe-Teach-Education-Geography-Toy-Map-Balloon-Beach-Ball-Free.jpg_220x220.jpg",
                        "AliExpress.com Product - 2017 Hot Sales 40CM Inflatable World Globe Teach Education Geography Toy Map Balloon Beach Ball Free Shipping NNA"),
                new Products("http://s.click.aliexpress.com/e/y3rB2rR",
                        "https://ae01.alicdn.com/kf/HTB1l9nAMVXXXXcqaXXXq6xXFXXXW/TS-New-Wireless-Girls-boys-LED-Microphone-Mic-Karaoke-Singing-Kids-Funny-Gift-Music-Toy-Pink.jpg_220x220.jpg",
                        "AliExpress.com Product - TS  New Wireless Girls boys LED Microphone Mic Karaoke Singing Kids Funny Gift Music Toy Pink AUG 25"),
                new Products("http://s.click.aliexpress.com/e/VRBqbY7",
                        "https://ae01.alicdn.com/kf/HTB15APmeEQIL1JjSZFhq6yDZFXak/H-A-Ultra-Thin-Cases-For-Iphone-6-s-6-plus-case-Luxury-Smooth-Matte-Shockproof.jpg_220x220.jpg",
                        "AliExpress.com Product - H&A Ultra Thin Cases For Iphone 6 s 6 plus case Luxury Smooth Matte Shockproof Back Cover Case For Iphone 6S Plus"),
                new Products("http://s.click.aliexpress.com/e/MrJQN7Y",
                        "https://ae01.alicdn.com/kf/HTB1JBygi3fH8KJjy1zcq6ATzpXaq/Cafele-USB-Type-C-for-Xiaomi-A1-Type-C-Cable-for-Huawei-Mate-10-Pro-Type.jpg_220x220.jpg",
                        "AliExpress.com Product - Cafele USB Type C for Xiaomi A1 Type C Cable for Huawei Mate 10 Pro Type C Fast Charge 5V 2.4A USB Type-c Cable"),
                new Products("http://s.click.aliexpress.com/e/RbEmAYR",
                        "https://ae01.alicdn.com/kf/HTB1uA0Ei_nI8KJjSszgq6A8ApXan/Cafele-for-iPhone-Cable-8-7-6-5-SE-USB-Cable-Nylon-Woven-Fast-Charger-Cable.jpg_220x220.jpg",
                        "AliExpress.com Product - Cafele for iPhone Cable 8 7 6 5 SE USB Cable Nylon Woven Fast Charger Cable USB Cable for iPhone DC 5V 1A"),
                new Products("http://s.click.aliexpress.com/e/zN72rzB",
                        "https://ae01.alicdn.com/kf/HTB1mZoVmfNNTKJjSspfq6zXIFXa3/JEASUNG-P8-Waterproof-new-Rugged-mobile-phone-IP68-4G-Shockproof-2G-RAM-16GB-ROM-Smartphone-5.jpg_220x220.jpg",
                        "AliExpress.com Product - JEASUNG P8 Waterproof new mobile phone IP68 4G Shockproof Phone 2G RAM 16GB ROM Smartphone 5\" NFC Fingerprint PTT IP67 Phone"),
                new Products("http://s.click.aliexpress.com/e/be66q37",
                        "https://ae01.alicdn.com/kf/HTB18RN5ecrI8KJjy0Fhq6zfnpXak/Office-Bags-Business-Summaries-Vintage-Style-PU-Leather-Briefcases-Men-Bags-Briefcase-Leather-Bag-Solid-Office.jpg_220x220.jpg",
                        "AliExpress.com Product - 2016 fashion Rero Vintage Style Crazy Horse PU Leather Men Briefcase Bag Solid Office Men Business Bags New"),
                new Products("http://s.click.aliexpress.com/e/aqVnYFa",
                        "https://ae01.alicdn.com/kf/HTB1bEcHkvDH8KJjy1Xcq6ApdXXaO/OCARDIAN-High-quality-Women-Leather-Small-Mini-Wallet-Holder-Zip-Coin-Purse-Clutch-Handbag-170428.jpg_220x220.jpg",
                        "AliExpress.com Product - High quality Women Leather Small Mini Wallet  Holder Zip Coin Purse Clutch Handbag 170428"),
                new Products("http://s.click.aliexpress.com/e/rVfaUNj",
                        "https://ae01.alicdn.com/kf/HTB1mc2BeH_I8KJjy1Xaq6zsxpXaQ/Women-Makeup-bag-New-Arrivals-Top-Quality-Zipper-Pencil-Case-Cute-Portable-Key-Coin-Purse-Bolsa.jpg_220x220.jpg",
                        "AliExpress.com Product - Women Makeup bag New Arrivals Top Quality Zipper Pencil Case Cute Portable Key Coin Purse Bolsa de maquillaje 17Apr29"),
                new Products("http://s.click.aliexpress.com/e/6qnEQzV",
                        "https://ae01.alicdn.com/kf/HTB1OOb2dlHH8KJjy0Fbq6AqlpXaa/Fashion-New-Wholesale-Square-Bow-Stripe-Cosmetic-Bag-Makeup-Bag-19-12-11cm-DropShipping-Hot.jpg_220x220.jpg",
                        "AliExpress.com Product - Fashion  New Wholesale Square Bow Stripe Cosmetic Bag Makeup Bag 19*12*11cm DropShipping  Hot"),
                new Products("http://s.click.aliexpress.com/e/MZzBAaU",
                        "https://ae01.alicdn.com/kf/HTB1wOGEj3oQMeJjy0Fpq6ATxpXao/Deanfun-3PCS-set-Women-Printed-Unicorn-Backpack-School-Bags-For-Teenage-Girls-Shoulder-Drawstring-Bags.jpg_220x220.jpg",
                        "AliExpress.com Product - Deanfun 3PCS /set Women Printed Unicorn Backpack School Bags For Teenage Girls Shoulder Drawstring Bags"),
                new Products("http://s.click.aliexpress.com/e/qfamQBe",
                        "https://ae01.alicdn.com/kf/HTB1r8eDa0nJ8KJjSszdq6yxuFXa9/PCSsole-technology-E-TPU-popcorn-insoles-high-elasticity-light-weight-shock-absorption-shoes-pad-for-man.jpg_220x220.jpg",
                        "AliExpress.com Product - PCSsole technology E-TPU popcorn insoles high elasticity light weight shock absorption shoes pad for man and women boost C1007"),
                new Products("http://s.click.aliexpress.com/e/iqzvNZr",
                        "https://ae01.alicdn.com/kf/HTB1939oQFXXXXciXFXXq6xXFXXXO/Women-Watches-Fashion-Leather-Vintage-Weave-Wrap-Quartz-Wrist-Watch-Bracelet-Watch-Charm-relogio-feminino-dropshipping.jpg_220x220.jpg",
                        "AliExpress.com Product - New Fashion Leather Retro Vintage Weave Wrap Quartz Wrist Watch Bracelet Watch for Women Lady Multi Colors High Quality,Nov 30"),
                new Products("http://s.click.aliexpress.com/e/AuF2zVn",
                        "https://ae01.alicdn.com/kf/HTB1AXBRLpXXXXabXVXXq6xXFXXX3/JW-Brand-Luxury-Crystal-Rose-Gold-Watches-Women-Fashion-Bracelet-Quartz-Watch-Women-Dress-Watch-Relogio.jpg_220x220.jpg",
                        "AliExpress.com Product - JW Brand Luxury Crystal Rose Gold Watches Women Fashion Bracelet Quartz Watch Women Dress Watch Relogio Feminino orologio donna"),
                new Products("http://s.click.aliexpress.com/e/RBaQN37",
                        "https://ae01.alicdn.com/kf/HTB1eLoXRVXXXXaNXVXXq6xXFXXXp/TENSKE-2017-Kitchen-Sink-7Color-Change-Water-Glow-Water-Stream-Shower-LED-Faucet-Taps-Light-levert.jpg_220x220.jpg",
                        "AliExpress.com Product - TENSKE 2017 Kitchen Sink 7Color Change Water Glow Water Stream Shower LED Faucet Taps Light levert dropship 2Jun27"),
                new Products("http://s.click.aliexpress.com/e/m2jyZvV",
                        "https://ae01.alicdn.com/kf/HTB1NxIgc2jM8KJjSZFsq6xdZpXa2/Alice-2018-Attractive-Robe-Mariee-A-line-Gowns-Sexy-Wedding-Dress-High-Quality-Lace-Bride-Dresses.jpg_220x220.jpg",
                        "AliExpress.com Product - Alice 2018 Attractive Robe Mariee A-line Gowns Sexy Wedding Dress High Quality Lace Bride Dresses Vestido De Noiva"),
                new Products("http://s.click.aliexpress.com/e/aiU7YNV",
                        "https://ae01.alicdn.com/kf/HTB16gz9SpXXXXbEXVXXq6xXFXXXH/ZUOYITING-Wedding-Accessories-2017-Appliques-Tulle-Long-Cathedral-Wedding-Veil-Lace-Edge-Bridal-Veil-with-Comb.jpg_220x220.jpg",
                        "AliExpress.com Product - ZUOYITING Wedding Accessories 2017 Appliques Tulle Long Cathedral Wedding Veil Lace Edge Bridal Veil with Comb veu de noiva long"),
                new Products("http://s.click.aliexpress.com/e/mU76Mja",
                        "https://ae01.alicdn.com/kf/HTB1.MZDmjihSKJjy0Flq6ydEXXav/Dressv-Sheath-Knee-Length-Mother-Of-The-Bride-Dress-Half-Sleeves-Appliques-Pleats-Formal-Gown-Mother.jpg_220x220.jpg",
                        "AliExpress.com Product - Dressv Sheath Knee Length Mother Of The Bride Dress Half Sleeves Appliques Pleats Formal Gown Mother of The Bride Dress Custom"),
                new Products("http://s.click.aliexpress.com/e/vfAmAme",
                        "https://ae01.alicdn.com/kf/HTB1k1F.b8fM8KJjSZPiq6xdspXaC/Angel-Tree-Custom-Made-Sleeveless-O-Neck-Embroidery-Crystal-Mermaid-Wedding-Dress-2018-Wedding-Dresses-Trumpet.jpg_220x220.jpg",
                        "AliExpress.com Product - Angel Tree Custom Made Sleeveless O-Neck Embroidery Crystal Mermaid Wedding Dress 2018 Wedding Dresses Trumpet Court Train"),
                new Products("http://s.click.aliexpress.com/e/nune6ia",
                        "https://ae01.alicdn.com/kf/HTB11od_iwn.PuJjSZFkq6A_lpXar/2017-Beach-Maid-of-Honor-Sky-Blue-Chiffon-A-Line-Bridesmaids-Dress-Long-Sequins-Formal-Sexy.jpg_220x220.jpg",
                        "AliExpress.com Product - 2017 Beach Maid of Honor Sky Blue Chiffon A Line Bridesmaids Dress Long Sequins Formal Sexy Wedding Party Gowns Custom Made"),
                new Products("http://s.click.aliexpress.com/e/2jAamub",
                        "https://ae01.alicdn.com/kf/HTB1hTEhax6I8KJjy0Fgq6xXzVXaX/1000Pcs-Lot-Rose-Petals-Mariage-Wedding-Decoration-Flowers-Petalas-Petalos-de-Rosa-Silk-Rose-Petal-Many.jpg_220x220.jpg",
                        "AliExpress.com Product - wedding accessories rose petals wedding table decoration rose petals for weddings Free Shipping AV33"),
                new Products("http://s.click.aliexpress.com/e/MvzjyfM",
                        "https://ae01.alicdn.com/kf/HTB18suBdxTI8KJjSspiq6zM4FXap/DOW-AMOUR-Polarized-Sunglasses-men-Brand-Driving-Glasses-Boating-Goggles-sports-Driver-Eyewear-Women-Male-Reduce.jpg_220x220.jpg",
                        "AliExpress.com Product - DOW AMOUR  Polarized Sunglasses men Brand Driving Glasses Boating Goggles sports Driver Eyewear Women Male Reduce Glare"),
                new Products("http://s.click.aliexpress.com/e/VFYBuny",
                        "https://ae01.alicdn.com/kf/HTB137JPfILJ8KJjy0Fnq6AFDpXaD/Basketball-Pendant-Necklace-Gold-Stainless-Steel-Chain-Necklace-Women-Men-Sport-Hip-Hop-Jewelry-Basketball-Lovers.jpg_220x220.jpg",
                        "AliExpress.com Product - Basketball Pendant Necklace Stainless Steel Chain Golden State Warriors NBA Fan Necklace Women Men Sport Team Jewelry"),
                new Products("http://s.click.aliexpress.com/e/nUBEAMJ",
                        "https://ae01.alicdn.com/kf/HTB1D41AnrsTMeJjSszgq6ycpFXap/Hot-Sale-6Pcs-Lot-Baby-Bed-Bumper-in-the-Crib-Cot-Bumper-Baby-Bed-Protector-Crib.jpg_220x220.jpg",
                        "AliExpress.com Product - 6Pcs/Lot Baby Bed Bumper Cotton Blend Baby Bedding Set for Newborns Toddle Children's Bed Protector Cot Bumper Crib Bumpers"),
                new Products("http://s.click.aliexpress.com/e/nUJ2jmm",
                        "https://ae01.alicdn.com/kf/HTB1n7JZavMTUeJjSZFKq6ygopXaX/Toddler-Kids-Kneepad-Protector-Soft-Thicken-Terry-Non-Slip-Dispensing-Safety-Crawling-Baby-Leg-Warmers-Well.jpg_220x220.jpg",
                        "AliExpress.com Product - Toddler Kids Kneepad Protector Soft Thicken Terry Non-Slip Dispensing Safety Crawling Baby Leg Warmers Well Knee Pads For Child"),
                new Products("http://s.click.aliexpress.com/e/6YFIyNr",
                        "https://ae01.alicdn.com/kf/HTB1S9I6XoMgYeJjSZFGq6xsMXXa7/8Pcs-Baby-Clothing-Sets-Autumn-Baby-Girl-Clothes-Cotton-Newborn-Clothes-Roupas-Bebe-Infant-Baby-Girl.jpg_220x220.jpg",
                        "AliExpress.com Product - 8Pcs Baby Clothing Sets Autumn Baby Girl Clothes Cotton Newborn Clothes Roupas Bebe Infant Baby Girl Clothes Baby Rompers+Pants"),
                new Products("http://s.click.aliexpress.com/e/7iu3zfE",
                        "https://ae01.alicdn.com/kf/HTB14N3fcBoHL1JjSZFwq6z6vpXaa/Children-s-Suit-Baby-Boy-Clothes-Set-Cotton-Long-Sleeve-Sets-For-Newborn-Baby-Boys-Outfits.jpg_220x220.jpg",
                        "AliExpress.com Product - Children Suit Baby Boy Clothes Set Cotton Fashion Brand Infant Sets For Newborns Cartoon Baby Boy Girl Clothing Kids Sleep Suits"),
        };
    }
}
